export interface Surah {
  number: number;
  name: string;
  arabicName: string;
  verses: number;
  juz: number; 
}

export interface Juz {
  number: number;
  name: string; 
  arabicName: string; 
  startSurah: number;
  startVerse: number;
  endSurah: number;
  endVerse: number;
}

export const surahs: Surah[] = [
  { number: 1, name: 'Al-Fatihah', arabicName: 'الفاتحة', verses: 7, juz: 1 },
  { number: 2, name: 'Al-Baqarah', arabicName: 'البقرة', verses: 286, juz: 1 },
  { number: 3, name: 'Aal-Imran', arabicName: 'آل عمران', verses: 200, juz: 3 },
  { number: 4, name: 'An-Nisa', arabicName: 'النساء', verses: 176, juz: 4 },
  { number: 5, name: "Al-Ma'idah", arabicName: 'المائدة', verses: 120, juz: 6 },
  { number: 6, name: "Al-An'am", arabicName: 'الأنعام', verses: 165, juz: 7 },
  { number: 7, name: "Al-A'raf", arabicName: 'الأعراف', verses: 206, juz: 8 },
  { number: 8, name: 'Al-Anfal', arabicName: 'الأنفال', verses: 75, juz: 9 },
  { number: 9, name: 'At-Tawbah', arabicName: 'التوبة', verses: 129, juz: 10 },
  { number: 10, name: 'Yunus', arabicName: 'يونس', verses: 109, juz: 11 },
  { number: 11, name: 'Hud', arabicName: 'هود', verses: 123, juz: 11 },
  { number: 12, name: 'Yusuf', arabicName: 'يوسف', verses: 111, juz: 12 },
  { number: 13, name: "Ar-Ra'd", arabicName: 'الرعد', verses: 43, juz: 13 },
  { number: 14, name: 'Ibrahim', arabicName: 'إبراهيم', verses: 52, juz: 13 },
  { number: 15, name: 'Al-Hijr', arabicName: 'الحجر', verses: 99, juz: 14 },
  { number: 16, name: 'An-Nahl', arabicName: 'النحل', verses: 128, juz: 14 },
  { number: 17, name: 'Al-Isra', arabicName: 'الإسراء', verses: 111, juz: 15 },
  { number: 18, name: 'Al-Kahf', arabicName: 'الكهف', verses: 110, juz: 15 },
  { number: 19, name: 'Maryam', arabicName: 'مريم', verses: 98, juz: 16 },
  { number: 20, name: 'Ta-Ha', arabicName: 'طه', verses: 135, juz: 16 },
  {
    number: 21,
    name: 'Al-Anbiya',
    arabicName: 'الأنبياء',
    verses: 112,
    juz: 17,
  },
  { number: 22, name: 'Al-Hajj', arabicName: 'الحج', verses: 78, juz: 17 },
  {
    number: 23,
    name: "Al-Mu'minun",
    arabicName: 'المؤمنون',
    verses: 118,
    juz: 18,
  },
  { number: 24, name: 'An-Nur', arabicName: 'النور', verses: 64, juz: 18 },
  { number: 25, name: 'Al-Furqan', arabicName: 'الفرقان', verses: 77, juz: 18 },
  {
    number: 26,
    name: "Ash-Shu'ara",
    arabicName: 'الشعراء',
    verses: 227,
    juz: 19,
  },
  { number: 27, name: 'An-Naml', arabicName: 'النمل', verses: 93, juz: 19 },
  { number: 28, name: 'Al-Qasas', arabicName: 'القصص', verses: 88, juz: 20 },
  {
    number: 29,
    name: 'Al-Ankabut',
    arabicName: 'العنكبوت',
    verses: 69,
    juz: 20,
  },
  { number: 30, name: 'Ar-Rum', arabicName: 'الروم', verses: 60, juz: 21 },
  { number: 31, name: 'Luqman', arabicName: 'لقمان', verses: 34, juz: 21 },
  { number: 32, name: 'As-Sajdah', arabicName: 'السجدة', verses: 30, juz: 21 },
  { number: 33, name: 'Al-Ahzab', arabicName: 'الأحزاب', verses: 73, juz: 21 },
  { number: 34, name: 'Saba', arabicName: 'سبأ', verses: 54, juz: 22 },
  { number: 35, name: 'Fatir', arabicName: 'فاطر', verses: 45, juz: 22 },
  { number: 36, name: 'Ya-Sin', arabicName: 'يس', verses: 83, juz: 22 },
  {
    number: 37,
    name: 'As-Saffat',
    arabicName: 'الصافات',
    verses: 182,
    juz: 23,
  },
  { number: 38, name: 'Sad', arabicName: 'ص', verses: 88, juz: 23 },
  { number: 39, name: 'Az-Zumar', arabicName: 'الزمر', verses: 75, juz: 23 },
  { number: 40, name: 'Ghafir', arabicName: 'غافر', verses: 85, juz: 24 },
  { number: 41, name: 'Fussilat', arabicName: 'فصلت', verses: 54, juz: 24 },
  { number: 42, name: 'Ash-Shura', arabicName: 'الشورى', verses: 53, juz: 25 },
  { number: 43, name: 'Az-Zukhruf', arabicName: 'الزخرف', verses: 89, juz: 25 },
  { number: 44, name: 'Ad-Dukhan', arabicName: 'الدخان', verses: 59, juz: 25 },
  {
    number: 45,
    name: 'Al-Jathiyah',
    arabicName: 'الجاثية',
    verses: 37,
    juz: 25,
  },
  { number: 46, name: 'Al-Ahqaf', arabicName: 'الأحقاف', verses: 35, juz: 26 },
  { number: 47, name: 'Muhammad', arabicName: 'محمد', verses: 38, juz: 26 },
  { number: 48, name: 'Al-Fath', arabicName: 'الفتح', verses: 29, juz: 26 },
  {
    number: 49,
    name: 'Al-Hujurat',
    arabicName: 'الحجرات',
    verses: 18,
    juz: 26,
  },
  { number: 50, name: 'Qaf', arabicName: 'ق', verses: 45, juz: 26 },
  {
    number: 51,
    name: 'Adh-Dhariyat',
    arabicName: 'الذاريات',
    verses: 60,
    juz: 26,
  },
  { number: 52, name: 'At-Tur', arabicName: 'الطور', verses: 49, juz: 27 },
  { number: 53, name: 'An-Najm', arabicName: 'النجم', verses: 62, juz: 27 },
  { number: 54, name: 'Al-Qamar', arabicName: 'القمر', verses: 55, juz: 27 },
  { number: 55, name: 'Ar-Rahman', arabicName: 'الرحمن', verses: 78, juz: 27 },
  {
    number: 56,
    name: "Al-Waqi'ah",
    arabicName: 'الواقعة',
    verses: 96,
    juz: 27,
  },
  { number: 57, name: 'Al-Hadid', arabicName: 'الحديد', verses: 29, juz: 27 },
  {
    number: 58,
    name: 'Al-Mujadilah',
    arabicName: 'المجادلة',
    verses: 22,
    juz: 28,
  },
  { number: 59, name: 'Al-Hashr', arabicName: 'الحشر', verses: 24, juz: 28 },
  {
    number: 60,
    name: 'Al-Mumtahanah',
    arabicName: 'الممتحنة',
    verses: 13,
    juz: 28,
  },
  { number: 61, name: 'As-Saff', arabicName: 'الصف', verses: 14, juz: 28 },
  { number: 62, name: "Al-Jumu'ah", arabicName: 'الجمعة', verses: 11, juz: 28 },
  {
    number: 63,
    name: 'Al-Munafiqun',
    arabicName: 'المنافقون',
    verses: 11,
    juz: 28,
  },
  {
    number: 64,
    name: 'At-Taghabun',
    arabicName: 'التغابن',
    verses: 18,
    juz: 28,
  },
  { number: 65, name: 'At-Talaq', arabicName: 'الطلاق', verses: 12, juz: 28 },
  { number: 66, name: 'At-Tahrim', arabicName: 'التحريم', verses: 12, juz: 28 },
  { number: 67, name: 'Al-Mulk', arabicName: 'الملك', verses: 30, juz: 29 },
  { number: 68, name: 'Al-Qalam', arabicName: 'القلم', verses: 52, juz: 29 },
  { number: 69, name: 'Al-Haqqah', arabicName: 'الحاقة', verses: 52, juz: 29 },
  {
    number: 70,
    name: "Al-Ma'arij",
    arabicName: 'المعارج',
    verses: 44,
    juz: 29,
  },
  { number: 71, name: 'Nuh', arabicName: 'نوح', verses: 28, juz: 29 },
  { number: 72, name: 'Al-Jinn', arabicName: 'الجن', verses: 28, juz: 29 },
  {
    number: 73,
    name: 'Al-Muzzammil',
    arabicName: 'المزمل',
    verses: 20,
    juz: 29,
  },
  {
    number: 74,
    name: 'Al-Muddathir',
    arabicName: 'المدثر',
    verses: 56,
    juz: 29,
  },
  {
    number: 75,
    name: 'Al-Qiyamah',
    arabicName: 'القيامة',
    verses: 40,
    juz: 29,
  },
  { number: 76, name: 'Al-Insan', arabicName: 'الإنسان', verses: 31, juz: 29 },
  {
    number: 77,
    name: 'Al-Mursalat',
    arabicName: 'المرسلات',
    verses: 50,
    juz: 29,
  },
  { number: 78, name: 'An-Naba', arabicName: 'النبأ', verses: 40, juz: 30 },
  {
    number: 79,
    name: "An-Nazi'at",
    arabicName: 'النازعات',
    verses: 46,
    juz: 30,
  },
  { number: 80, name: 'Abasa', arabicName: 'عبس', verses: 42, juz: 30 },
  { number: 81, name: 'At-Takwir', arabicName: 'التكوير', verses: 29, juz: 30 },
  {
    number: 82,
    name: 'Al-Infitar',
    arabicName: 'الانفطار',
    verses: 19,
    juz: 30,
  },
  {
    number: 83,
    name: 'Al-Mutaffifin',
    arabicName: 'المطففين',
    verses: 36,
    juz: 30,
  },
  {
    number: 84,
    name: 'Al-Inshiqaq',
    arabicName: 'الانشقاق',
    verses: 25,
    juz: 30,
  },
  { number: 85, name: 'Al-Buruj', arabicName: 'البروج', verses: 22, juz: 30 },
  { number: 86, name: 'At-Tariq', arabicName: 'الطارق', verses: 17, juz: 30 },
  { number: 87, name: "Al-A'la", arabicName: 'الأعلى', verses: 19, juz: 30 },
  {
    number: 88,
    name: 'Al-Ghashiyah',
    arabicName: 'الغاشية',
    verses: 26,
    juz: 30,
  },
  { number: 89, name: 'Al-Fajr', arabicName: 'الفجر', verses: 30, juz: 30 },
  { number: 90, name: 'Al-Balad', arabicName: 'البلد', verses: 20, juz: 30 },
  { number: 91, name: 'Ash-Shams', arabicName: 'الشمس', verses: 15, juz: 30 },
  { number: 92, name: 'Al-Layl', arabicName: 'الليل', verses: 21, juz: 30 },
  { number: 93, name: 'Ad-Duha', arabicName: 'الضحى', verses: 11, juz: 30 },
  { number: 94, name: 'Ash-Sharh', arabicName: 'الشرح', verses: 8, juz: 30 },
  { number: 95, name: 'At-Tin', arabicName: 'التين', verses: 8, juz: 30 },
  { number: 96, name: 'Al-Alaq', arabicName: 'العلق', verses: 19, juz: 30 },
  { number: 97, name: 'Al-Qadr', arabicName: 'القدر', verses: 5, juz: 30 },
  { number: 98, name: 'Al-Bayyinah', arabicName: 'البينة', verses: 8, juz: 30 },
  {
    number: 99,
    name: 'Az-Zalzalah',
    arabicName: 'الزلزلة',
    verses: 8,
    juz: 30,
  },
  {
    number: 100,
    name: 'Al-Adiyat',
    arabicName: 'العاديات',
    verses: 11,
    juz: 30,
  },
  {
    number: 101,
    name: "Al-Qari'ah",
    arabicName: 'القارعة',
    verses: 11,
    juz: 30,
  },
  {
    number: 102,
    name: 'At-Takathur',
    arabicName: 'التكاثر',
    verses: 8,
    juz: 30,
  },
  { number: 103, name: 'Al-Asr', arabicName: 'العصر', verses: 3, juz: 30 },
  { number: 104, name: 'Al-Humazah', arabicName: 'الهمزة', verses: 9, juz: 30 },
  { number: 105, name: 'Al-Fil', arabicName: 'الفيل', verses: 5, juz: 30 },
  { number: 106, name: 'Quraysh', arabicName: 'قريش', verses: 4, juz: 30 },
  { number: 107, name: "Al-Ma'un", arabicName: 'الماعون', verses: 7, juz: 30 },
  { number: 108, name: 'Al-Kawthar', arabicName: 'الكوثر', verses: 3, juz: 30 },
  {
    number: 109,
    name: 'Al-Kafirun',
    arabicName: 'الكافرون',
    verses: 6,
    juz: 30,
  },
  { number: 110, name: 'An-Nasr', arabicName: 'النصر', verses: 3, juz: 30 },
  { number: 111, name: 'Al-Masad', arabicName: 'المسد', verses: 5, juz: 30 },
  { number: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', verses: 4, juz: 30 },
  { number: 113, name: 'Al-Falaq', arabicName: 'الفلق', verses: 5, juz: 30 },
  { number: 114, name: 'An-Nas', arabicName: 'الناس', verses: 6, juz: 30 },
];

export const juzs: Juz[] = [
  {
    number: 1,
    name: 'Juz 1',
    arabicName: 'الجزء الأول',
    startSurah: 1,
    startVerse: 1,
    endSurah: 2,
    endVerse: 141,
  },
  {
    number: 2,
    name: 'Juz 2',
    arabicName: 'الجزء الثاني',
    startSurah: 2,
    startVerse: 142,
    endSurah: 2,
    endVerse: 252,
  },
  {
    number: 3,
    name: 'Juz 3',
    arabicName: 'الجزء الثالث',
    startSurah: 2,
    startVerse: 253,
    endSurah: 3,
    endVerse: 92,
  },
  {
    number: 4,
    name: 'Juz 4',
    arabicName: 'الجزء الرابع',
    startSurah: 3,
    startVerse: 93,
    endSurah: 4,
    endVerse: 23,
  },
  {
    number: 5,
    name: 'Juz 5',
    arabicName: 'الجزء الخامس',
    startSurah: 4,
    startVerse: 24,
    endSurah: 4,
    endVerse: 147,
  },
  {
    number: 6,
    name: 'Juz 6',
    arabicName: 'الجزء السادس',
    startSurah: 4,
    startVerse: 148,
    endSurah: 5,
    endVerse: 81,
  },
  {
    number: 7,
    name: 'Juz 7',
    arabicName: 'الجزء السابع',
    startSurah: 5,
    startVerse: 82,
    endSurah: 6,
    endVerse: 110,
  },
  {
    number: 8,
    name: 'Juz 8',
    arabicName: 'الجزء الثامن',
    startSurah: 6,
    startVerse: 111,
    endSurah: 7,
    endVerse: 87,
  },
  {
    number: 9,
    name: 'Juz 9',
    arabicName: 'الجزء التاسع',
    startSurah: 7,
    startVerse: 88,
    endSurah: 8,
    endVerse: 40,
  },
  {
    number: 10,
    name: 'Juz 10',
    arabicName: 'الجزء العاشر',
    startSurah: 8,
    startVerse: 41,
    endSurah: 9,
    endVerse: 92,
  },
  {
    number: 11,
    name: 'Juz 11',
    arabicName: 'الجزء الحادي عشر',
    startSurah: 9,
    startVerse: 93,
    endSurah: 11,
    endVerse: 5,
  },
  {
    number: 12,
    name: 'Juz 12',
    arabicName: 'الجزء الثاني عشر',
    startSurah: 11,
    startVerse: 6,
    endSurah: 12,
    endVerse: 52,
  },
  {
    number: 13,
    name: 'Juz 13',
    arabicName: 'الجزء الثالث عشر',
    startSurah: 12,
    startVerse: 53,
    endSurah: 14,
    endVerse: 52,
  },
  {
    number: 14,
    name: 'Juz 14',
    arabicName: 'الجزء الرابع عشر',
    startSurah: 15,
    startVerse: 1,
    endSurah: 16,
    endVerse: 128,
  },
  {
    number: 15,
    name: 'Juz 15',
    arabicName: 'الجزء الخامس عشر',
    startSurah: 17,
    startVerse: 1,
    endSurah: 18,
    endVerse: 74,
  },
  {
    number: 16,
    name: 'Juz 16',
    arabicName: 'الجزء السادس عشر',
    startSurah: 18,
    startVerse: 75,
    endSurah: 20,
    endVerse: 135,
  },
  {
    number: 17,
    name: 'Juz 17',
    arabicName: 'الجزء السابع عشر',
    startSurah: 21,
    startVerse: 1,
    endSurah: 22,
    endVerse: 78,
  },
  {
    number: 18,
    name: 'Juz 18',
    arabicName: 'الجزء الثامن عشر',
    startSurah: 23,
    startVerse: 1,
    endSurah: 25,
    endVerse: 20,
  },
  {
    number: 19,
    name: 'Juz 19',
    arabicName: 'الجزء التاسع عشر',
    startSurah: 25,
    startVerse: 21,
    endSurah: 27,
    endVerse: 55,
  },
  {
    number: 20,
    name: 'Juz 20',
    arabicName: 'الجزء العشرون',
    startSurah: 27,
    startVerse: 56,
    endSurah: 29,
    endVerse: 45,
  },
  {
    number: 21,
    name: 'Juz 21',
    arabicName: 'الجزء الحادي والعشرون',
    startSurah: 29,
    startVerse: 46,
    endSurah: 33,
    endVerse: 30,
  },
  {
    number: 22,
    name: 'Juz 22',
    arabicName: 'الجزء الثاني والعشرون',
    startSurah: 33,
    startVerse: 31,
    endSurah: 36,
    endVerse: 27,
  },
  {
    number: 23,
    name: 'Juz 23',
    arabicName: 'الجزء الثالث والعشرون',
    startSurah: 36,
    startVerse: 28,
    endSurah: 39,
    endVerse: 31,
  },
  {
    number: 24,
    name: 'Juz 24',
    arabicName: 'الجزء الرابع والعشرون',
    startSurah: 39,
    startVerse: 32,
    endSurah: 41,
    endVerse: 46,
  },
  {
    number: 25,
    name: 'Juz 25',
    arabicName: 'الجزء الخامس والعشرون',
    startSurah: 41,
    startVerse: 47,
    endSurah: 45,
    endVerse: 37,
  },
  {
    number: 26,
    name: 'Juz 26',
    arabicName: 'الجزء السادس والعشرون',
    startSurah: 46,
    startVerse: 1,
    endSurah: 51,
    endVerse: 30,
  },
  {
    number: 27,
    name: 'Juz 27',
    arabicName: 'الجزء السابع والعشرون',
    startSurah: 51,
    startVerse: 31,
    endSurah: 57,
    endVerse: 29,
  },
  {
    number: 28,
    name: 'Juz 28',
    arabicName: 'الجزء الثامن والعشرون',
    startSurah: 58,
    startVerse: 1,
    endSurah: 66,
    endVerse: 12,
  },
  {
    number: 29,
    name: 'Juz 29',
    arabicName: 'الجزء التاسع والعشرون',
    startSurah: 67,
    startVerse: 1,
    endSurah: 77,
    endVerse: 50,
  },
  {
    number: 30,
    name: 'Juz 30',
    arabicName: 'الجزء الثلاثون',
    startSurah: 78,
    startVerse: 1,
    endSurah: 114,
    endVerse: 6,
  },
];
